[project]
name = "image-uploader"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "b2sdk>=2.6.0",
    "black>=24.10.0",
    "flake8>=7.1.1",
    "pyright>=1.1.387",
    "ruff>=0.7.2",
]
